---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webserverapp.my.domain
  resources:
  - webservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webserverapp.my.domain
  resources:
  - webservers/finalizers
  verbs:
  - update
- apiGroups:
  - webserverapp.my.domain
  resources:
  - webservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - developments
  verbs:
  - create
  - delete
  - watch
  - patch
  - update
  - get
  - list
- apiGroups:
  - apps
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - watch
  - patch
  - update
  - get
  - list
